apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      security:
        authn:
          x509:
            enabled: true
            # roleOid: 1.2.840.10070.8.1
        apiSecurity:
          ssl:
            enabled: true
            keyAlias: gate
            keyStore: encryptedFile:k8s!n:spin-secrets!k:gate.jks
            keyStoreType: jks
            keyStorePassword: encrypted:k8s!n:spin-secrets!k:jks-password # The password to unlock your keystore. Due to a limitation in Tomcat, this must match your key's password in the keystore.
            trustStore: encryptedFile:k8s!n:spin-secrets!k:gate.jks
            trustStoreType: jks
            trustStorePassword: encrypted:k8s!n:spin-secrets!k:jks-password # The password to unlock your truststore.
            clientAuth: WANT # Declare 'WANT' when client auth is wanted but not mandatory, or 'NEED', when client auth is mandatory.
    profiles:
      gate:
        default:
          apiPort: 8085
      #       legacyServerPort: 8084
      #     server:
      #       port: 9002
      # service-settings:
      #   gate:
      #     scheme: http
  # expose:
  #   type: service
  #   service:
  #     type: LoadBalancer
  #     annotations:
  #       service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  #     overrides:
  #       gate-x509:
  #         annotations:
  #           service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  #           service.beta.kubernetes.io/aws-load-balancer-ssl-cert: null
  #         publicPort: 443

