#-----------------------------------------------------------------------------------------------------------------
# Example configuration for securing spinnaker with github credentials and github teams group membership.
#
# Documentation: https://spinnaker.io/setup/security/authentication/oauth/
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      security:
        authn:
          enabled: true
          oauth2:
            enabled: true
            client:
              clientId: 291160323967-j2hobu76g5ltn76kupnnfj9uif1m2j11.apps.googleusercontent.com                                   # The OAuth client ID you have configured with your OAuth provider.
              clientSecret: encrypted:k8s!n:spin-secrets!k:oauth-client-secret # (Secret). The OAuth client secret you have configured with your OAuth provider.
              accessTokenUri: https://www.googleapis.com/oauth2/v4/token      # Used to get an access token.
              userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth   # Used to get an authorization code.
              scope: profile email                                               # The scope for your OAuth provider, e.g. user:email
            resource:
              userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo                         # Used to the current user's profile.
            userInfoMapping:
              email: email
              firstName: given_name
              lastName: family_name                                               # The username field returned from your OAuth provider.
            provider: GOOGLE                                                   # One of AZURE, GITHUB, ORACLE, OTHER, GOOGLE        
        # authz:
        #   enabled: true
        #   groupMembership:
        #     service: GITHUB                             # One of EXTERNAL, FILE, GOOGLE, GITHUB, LDAP
        #     github:
        #       roleProviderType: GITHUB
        #       baseUrl: https://api.github.com           # Used if using GitHub enterprise or some other non github.com GitHub installation.
        #       accessToken: encrypted:k8s!n:spin-secrets!k:github-token  # (Secret). A personal access token of an account with access to your organization’s GitHub Teams structure. Supports encrypted value.
        #       organization: try-spinnaker-io                       # The GitHub organization under which to query for GitHub Teams.
