apiVersion: v1
data:
  index.html: >-
    <!DOCTYPE html>

    <html>

    <head>

    <style>

    h1 {text-align: center; font-family: "Garamond";}

    p {text-align: center;}

    div {text-align: center;}

    </style>

    </head>

    <body>


    <h1>Welcome to web-app!</h1>

    <p>Hosted by try.spinnaker.io</p>

    <div> <img
    src="https://spinnaker.io/images/spinnaker-logo-transparent-color.png"
    alt="spinnaker-logo"> </div>


    </body>

    </html>
kind: ConfigMap
metadata:
  name: index-for-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: 'nginx:latest'
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: index
              subPath: index.html
      volumes:
        - configMap:
            defaultMode: 420
            name: index-for-nginx
          name: index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
